on:
  push:
  pull_request:

name: CI
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        cache: [use-cache, no-cache]
        restore: [cache-restored, no-cache-restored]
        exclude:
          - cache: no-cache
            restore: cache-restored
    steps:
      - uses: actions/checkout@v4
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: info.keepass.KeePass.Devel-${{ matrix.cache }}-${{ matrix.restore }}.flatpak
          manifest-path: ./info.keepass.KeePass.yml
          cache: ${{ matrix.cache == 'use-cache' }}
          restore-cache: ${{ matrix.restore == 'cache-restored' }}
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.restore }}
          arch: ${{ matrix.arch }}
          verbose: true

  flatpak-builder-stop-at:
    name: Flatpak Builder Stop At
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Partial Build with Stop At
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: ./info.keepass.KeePass.yml
          stop-at-module: testproject
          cache: false
          verbose: true

  flatpak-builder-cache-hit:
    name: Flatpak Builder Cache Hit
    runs-on: ubuntu-latest
    needs: flatpak-builder
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Cache Hit Test
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: info.keepass.KeePass.Devel-cache-hit.flatpak
          manifest-path: ./info.keepass.KeePass.yml
          cache-key: flatpak-builder-${{ github.sha }}-no-cache-restored
          verbose: true

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --also=dev
        working-directory: flatpak-builder
      - run: yarn test
        working-directory: flatpak-builder

  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --also=dev
        working-directory: flatpak-builder
      - run: yarn run eslint .
        working-directory: flatpak-builder
      - run: yarn install --also=dev
        working-directory: flat-manager
      - run: yarn run eslint .
        working-directory: flat-manager
