on:
  push:
  pull_request:

name: CI

jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        cache: [use-cache, no-cache]
        restore: [cache-restored, no-cache-restored]
        exclude:
          - cache: no-cache
            restore: cache-restored
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensuring submodules are checked out

      - name: Cache Flatpak Builder dependencies
        if: ${{ matrix.cache == 'use-cache' }}
        uses: actions/cache@v2
        with:
          path: ~/.cache/flatpak  # Flatpak build cache location
          key: flatpak-builder-${{ github.sha }}-${{ matrix.cache }}
          restore-keys: |
            flatpak-builder-${{ github.sha }}-${{ matrix.cache }}
            flatpak-builder-${{ github.sha }}
            flatpak-builder-

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: info.keepass.KeePass.Devel-${{ matrix.cache }}-${{ matrix.restore }}.flatpak
          manifest-path: ./info.keepass.KeePass.yml
          cache: ${{ matrix.cache == 'use-cache' }}
          restore-cache: ${{ matrix.restore == 'cache-restored' }}
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.restore }}
          arch: ${{ matrix.arch }}
          verbose: true
